// SETTINGS CONSTANTS
export const LOGO_BG = 'LOGO_BG';
export const NAVBAR_BG = 'NAVBAR_BG';
export const SIDEBAR_BG = 'SIDEBAR_BG';
export const THEME = 'THEME';
export const DIRECTION = 'DIRECTION';
export const SIDEBAR_POSITION = 'SIDEBAR_POSITION';
export const HEADER_POSITION = 'HEADER_POSITION';
export const LAYOUT = 'LAYOUT';
export const SIDEBAR_TYPE = 'SIDEBAR_TYPE';


// VEHICLE CONSTANTS
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';
export const FETCH_VEHICLE_SUCCESS = 'FETCH_VEHICLE_SUCCESS';
export const FETCH_VEHICLE_DETAILS_SUCCESS = 'FETCH_VEHICLE_DETAILS_SUCCESS';
export const VEHICLE_NAME_LIST = 'VEHICLE_NAME_LIST';
export const UPDATE_VEHICLE_DETAILS = 'UPDATE_VEHICLE_DETAILS';


// VEHICLE ASSIGN CONSTANTS
export const FETCH_VEHICLE_ASSIGN_SUCCESS = 'FETCH_VEHICLE_ASSIGN_SUCCESS';
